"""OpenAI-style tool schemas for chat / MCP."""
from __future__ import annotations

# ——— schema 简写：让 20+ 个工具定义保持一屏可读 ———

_CODE = {"code": {"type": "string", "description": "6 位 A 股代码，如 600519"}}


def _t(name: str, desc: str, props: dict | None = None, required: list[str] | None = None) -> dict:
    return {
        "type": "function",
        "function": {
            "name": name,
            "description": desc,
            "parameters": {"type": "object", "properties": props or {}, "required": required or []},
        },
    }


def _pick(rows: list[dict], keys: tuple[str, ...] | None, limit: int) -> list[dict]:
    """取前 limit 条（控 token）；keys 为 None 时保留全部字段，只截条数。"""
    head = (rows or [])[:limit]
    if keys is None:
        return [r for r in head if isinstance(r, dict)]
    return [{k: r.get(k) for k in keys} for r in head if isinstance(r, dict)]


TOOLS: list[dict] = [
    # —— 行情与估值 ——
    _t("query_quote", "查 A 股实时行情：现价/涨跌/PE/PB/市值/换手/涨跌停。可批量。",
       {"codes": {"type": "array", "items": {"type": "string"}, "description": "6 位代码列表，如 ['600519','000858']"}},
       ["codes"]),
    _t("query_valuation", "查单只个股的完整估值：行情 + 机构一致预期 EPS + 前向 PE / PEG / PE 消化年数。",
       _CODE, ["code"]),
    _t("query_valuation_percentile",
       "查个股 PE-TTM / PB 的历史估值分位：当前值 + 近五年 20/50/80 分位带 + 当前所处百分位。判断估值贵贱先用这个。",
       _CODE, ["code"]),
    _t("query_kline",
       "查个股 K 线并附区间统计（起止价、区间涨跌幅、最高/最低、振幅）。判断价格位置与趋势用。",
       {**_CODE,
        "period": {"type": "string", "enum": ["day", "week", "month"], "description": "周期，默认 day"},
        "count": {"type": "integer", "description": "取最近多少根，默认 60，最大 250"}},
       ["code"]),

    # —— 基本面 ——
    _t("query_financials",
       "查个股最新报告期财务关键指标：营收/净利及同比、ROE、毛利率、净利率、每股经营现金流、EPS。",
       _CODE, ["code"]),
    _t("query_company_info", "查公司基本概况：所属行业、总股本/流通股、上市日期等。", _CODE, ["code"]),
    _t("query_reports", "查个股近期研报列表（标题/机构/评级/日期）。", _CODE, ["code"]),
    _t("query_news", "查个股近期新闻（标题/时间/来源）。", _CODE, ["code"]),
    _t("query_cls_telegraph",
       "查财联社电报：全市场实时财经快讯（标题/正文/时间）。客观公开资讯，不构成投资建议。",
       {"limit": {"type": "integer", "description": "条数，默认 30"}}, []),
    # —— 资金面与筹码 ——
    _t("query_fund_flow",
       "查个股资金流向：最近若干日主力/超大单/大单/中单/小单净流入，并附近 5 日、20 日累计主力净额。",
       {**_CODE, "days": {"type": "integer", "description": "明细返回最近多少日，默认 10，最大 60"}},
       ["code"]),
    _t("query_fund_flow_minute",
       "查个股当日分钟级主力/大小单净流入（东财）。返回最新点与全天主力累计。",
       _CODE, ["code"]),
    _t("query_ths_limit_up",
       "查同花顺涨停揭秘：涨停原因题材、板型、封板成功率、几天几板。客观公开榜单，不构成推荐。",
       {"date": {"type": "string", "description": "可选 YYYYMMDD，默认今天"}}, []),
    _t("query_margin", "查个股融资融券：融资余额、融资买入/偿还、融券余额趋势（最近若干期）。", _CODE, ["code"]),
    _t("query_holders", "查个股股东户数变化（户数增减 = 筹码集中或分散的直接证据）。", _CODE, ["code"]),
    _t("query_chips",
       "查个股筹码分布推演(获利比例/平均成本/90%成本区间/筹码峰). baostock 前复权+换手, 期初播种全部流通盘. 推演不是券商实测持仓.",
       {**_CODE,
        "start": {"type": "string", "description": "YYYY-MM-DD, 默认近 180 日"},
        "end": {"type": "string", "description": "YYYY-MM-DD, 默认今天"}},
       ["code"]),
    _t("query_valuation_history",
       "查个股日频估值史: PE-TTM / PB-MRQ / PS-TTM / 换手 / 停牌 / 当时是否 ST. baostock, 北交所不可用.",
       {**_CODE,
        "start": {"type": "string", "description": "YYYY-MM-DD, 默认近 365 日"},
        "end": {"type": "string", "description": "YYYY-MM-DD, 默认今天"}},
       ["code"]),
    _t("query_list_status",
       "查个股上市日 / 退市日 / 在市状态. baostock 是本站唯一能拿到退市日的零鉴权源. 北交所不可用.",
       _CODE, ["code"]),
    _t("query_sw_industry",
       "查个股在某日所属申万行业(代码, 官方不发布中文名). 用 as_of 消前视, 不要拿今天的行业套历史.",
       {**_CODE, "as_of": {"type": "string", "description": "YYYY-MM-DD, 默认今天"}},
       ["code"]),
    _t("query_etf_flow",
       "查全市场 ETF 资金流向排行：主力/超大/大/中/小单净流入（亿元）。客观公开榜单，不构成推荐。",
       {
           "sort_by": {"type": "string", "enum": ["net_inflow", "change_pct"], "description": "排序，默认 net_inflow"},
           "limit": {"type": "integer", "description": "条数，默认 30"},
       }, []),
    _t("query_etf_shares",
       "查单只 ETF 份额：沪市走上交所日频、深市走深交所日频，另附东财季报期间申购/赎回/期末份额（亿份）。默认 510300。客观公开数据，不构成推荐。",
       {
           "code": {"type": "string", "description": "6 位 ETF 代码，如 510050 / 510300 / 510500 / 588000 / 159915 / 159919"},
           "n": {"type": "integer", "description": "日线条数，默认 80"},
       }, []),
    _t("query_shareholder_changes",
       "查股东/高管增减持披露：变动人、增减方向、股数、均价、职务。可查全市场或指定个股。客观披露，不构成推荐。",
       {
           "code": {"type": "string", "description": "可选 6 位代码；空=全市场最近变动"},
           "change_type": {"type": "string", "enum": ["all", "增持", "减持"], "description": "默认 all"},
           "limit": {"type": "integer", "description": "条数，默认 30"},
       }, []),
    _t("query_lpr",
       "查 LPR 贷款市场报价利率历史（1Y/5Y）。全国银行间同业拆借中心公开报价。",
       {"days": {"type": "integer", "description": "回溯天数，默认 365"}}, []),
    _t("query_cn_bond_yield",
       "查中债国债或政策性金融债收益率曲线（1Y~30Y + 10Y-2Y/30Y-10Y 利差）。客观利率，非预测。",
       {"curve_type": {"type": "string", "enum": ["treasury", "policy"], "description": "默认 treasury"}}, []),
    _t("query_block_trade", "查个股大宗交易记录：成交价、折溢价率、成交量、买卖营业部。", _CODE, ["code"]),
    _t("query_dragon_tiger", "查个股龙虎榜：近 30 日上榜记录、最近一次买卖席位 TOP5、机构专用席位净买额。", _CODE, ["code"]),
    _t("query_daily_dragon_tiger",
       "查全市场龙虎榜：当日（或最近有数据交易日）上榜股票、上榜原因、买卖净额(万元)、涨跌幅。客观公开榜单，不构成推荐。",
       {
           "date": {"type": "string", "description": "可选 YYYY-MM-DD，默认最近有数据日"},
           "top": {"type": "integer", "description": "返回条数，默认 30"},
       }, []),
    _t("query_dividend", "查个股历史分红方案：每股派息、股息率、除权除息日、分红进度。", _CODE, ["code"]),

    # —— 事件与风险 ——
    _t("query_announcements", "查个股近期公告（标题/日期/类型）。查风险与重大事项先用这个。", _CODE, ["code"]),
    _t("query_lockup", "查个股限售解禁：历史解禁记录 + 未来 90 天待解禁事件（日期/类型/股数/占比）。", _CODE, ["code"]),
    _t("query_investor_qa", "查个股投资者互动易问答（公司对投资者提问的官方回复，常含经营细节）。", _CODE, ["code"]),

    # —— 行业与板块 ——
    _t("query_concepts", "查个股所属板块与概念归属，以及当下被市场归到哪些热门概念在炒。", _CODE, ["code"]),
    _t("query_industry_comparison", "查全市场行业板块横向对比：各行业涨跌幅、成交额、领涨股。看板块强弱用。",
       {"top_n": {"type": "integer", "description": "返回前 N 个行业，默认 20"}}),

    # —— 市场层 ——
    _t("query_market",
       "查大盘与市场情绪。scope: indices=A股指数 / global=全球指数 / emotion=短线情绪(连板梯队/封板率) / turnover=全市场成交额 TOP20 / overview=大盘总览(指数+情绪+板块资金流)。",
       {"scope": {"type": "string", "enum": ["indices", "global", "emotion", "turnover", "overview"],
                  "description": "要查的范围，默认 overview"}}),
    _t("query_news_radar",
       "查资讯雷达：12 条赛道的行业资讯聚合（非个股新闻，看产业面动态用）。可传 track 只看某条赛道（如「半导体」「AI」）。",
       {"track": {"type": "string", "description": "赛道名关键词，留空看全部"},
        "per_track": {"type": "integer", "description": "每条赛道取最新几条，默认 5"}}),

    # —— 海外 ——
    _t("query_global_stock",
       "查美股 / 港股 / 韩股个股：行情 + 关键财务指标（韩股仅行情）。美股用字母代码(AAPL)，港股用数字(00700)，韩股 6 位数字加 .KS(005930.KS)。",
       {"symbol": {"type": "string", "description": "美股字母代码 / 港股代码 / 韩股 XXXXXX.KS"}},
       ["symbol"]),
    _t("query_hk_cashflow",
       "查港股现金流量表：经营/投资/筹资活动现金流净额、现金及等价物净增加、期初/期末现金，多期、附同比。仅港股，代码用数字如 00700。",
       {"symbol": {"type": "string", "description": "港股代码，如 00700"}},
       ["symbol"]),

    # —— 期权 / 期货波动率（OpenVlab, 公开数据）——
    _t("query_ovlab_market",
       "查期权/期货波动率市场概览(OpenVlab): 全部品种的现价/涨跌幅/平值隐波/隐波变化/隐波百分位/22日实波/VolAlphaT/Carry/偏度及百分位/近远月动量/主力合约/到期日/夜盘/是否境外。看波动率全景、找高/低波品种用。",
       {"limit": {"type": "integer", "description": "返回前 N 个品种，默认全部，按原始顺序"}}),
    _t("query_ovlab_detail",
       "查单个期权/期货标的的详细数据(OpenVlab dto): 含主力合约月份、希腊字母、隐波曲线、各合约报价等。prod_und 用标的代码如 510300。",
       {"prod_und": {"type": "string", "description": "标的代码 (prodUnd)，如 510300 / 510050"},
        "exps": {"type": "array", "items": {"type": "string"}, "description": "可选, 指定主力合约月份列表"}},
       ["prod_und"]),
    _t("query_ovlab_volatility_ts",
       "查波动率期限结构汇总(OpenVlab volatility-ts-all): 各标的的隐波期限结构，看波动率随到期日的形态。部分字段可能受限。"),
    _t("query_ovlab_future_ts",
       "查期货期限结构(OpenVlab future-ts): scope=all 全品种汇总 / single 单品种(prod_und 如 MA)。期货版波动率期限结构。",
       {"scope": {"type": "string", "enum": ["all", "single"], "description": "all=全品种汇总, single=单品种"},
        "prod_und": {"type": "string", "description": "scope=single 时必填, 标的代码如 MA"}}),
    _t("query_ovlab_arb_board",
       "查套利看板(跨期近-次价差 / 跨品种近月价差 / 股指近月). 与网页 /arb 同源, 复用 future-ts. 只陈述价差事实, 不构成交易建议."),
    _t("query_ovlab_flow_alert",
       "查期权异动榜(OpenVlab flow-alert): 近期异动合约清单. 规则 r001_single_trade=成交异动(3秒单笔; side=ask 主动买上 / bid 主动卖下) / r002_1m_pct_move=走势异动(1分钟涨幅) / r003_repeated_aggressive_burst=连续成交(2秒同向单调). 含合约/到期日/区间涨幅/窗口成交量/权利金."),
    _t("query_ovlab_warehouse_history",
       "查单品种多年持仓历史(OpenVlab warehouse/history): product 如 MA。返回当前持仓 + year2013~2026 各年持仓 + ratioData + category。仓差/资金面/季节性分析用。",
       {"product": {"type": "string", "description": "品种代码, 如 MA / CU / RB"}},
       ["product"]),
    _t("query_ovlab_seasonal_history",
       "查全品种季节性持仓(OpenVlab warehouse/seasonal-history-all): 按年份分组的多品种持仓, 研究季节性规律用。years 留空取近 6 年。",
       {"years": {"type": "array", "items": {"type": "string"}, "description": "年份字符串列表, 如 ['2023','2024','2025']"},
        "product": {"type": "string", "description": "可选, 指定单品种"}}),
    _t("query_ovlab_product_exps",
       "查全品种合约月份列表(OpenVlab product-exps): 75 个品种各有哪些合约月份。查具体合约代码(K线/详情前置)用。prod_und 可选指定单品种。",
       {"prod_und": {"type": "string", "description": "可选, 指定单品种"}}),
    _t("query_ovlab_meta",
       "查OpenVlab元数据: scope=exchange 交易所信息 / sector 板块信息 / next_trading_day 下一交易日 / holidays 节假日(需 exchange)。",
       {"scope": {"type": "string", "enum": ["exchange", "sector", "next_trading_day", "holidays"],
                  "description": "要查的元数据类型"},
        "exchange": {"type": "string", "description": "scope=holidays 时必填, 交易所代码如 CZCE"}}),
    _t("query_ovlab_position",
       "查期权/期货持仓排名(OpenVlab option-position/future-position): 交易所每日公布的期货公司持仓排名榜。scope=products 品种列表 / details 持仓明细(买方/卖方/净多/净空排名+增减+净多净空第一)。kind=future 期货 / option 期权(需 direction C/P)。",
       {"scope": {"type": "string", "enum": ["products", "details"], "description": "products=品种列表, details=持仓明细"},
        "kind": {"type": "string", "enum": ["future", "option"], "description": "future=期货持仓, option=期权持仓"},
        "product": {"type": "string", "description": "scope=details 时必填, 品种如 RB/IO"},
        "code": {"type": "string", "description": "scope=details 时必填, 合约如 rb2608/IO2608"},
        "direction": {"type": "string", "enum": ["C", "P"], "description": "kind=option 时必填, C=Call P=Put"},
        "day": {"type": "string", "description": "scope=details 时必填, YYYY-MM-DD; products 返回 last_trading_day"}},
       []),
    _t("query_ovlab_chart",
       "查K线/ATM隐波历史(OpenVlab history/history-atmvol): 前端轻量图表同源数据。kind=kline K线OHLC+持仓+成交量 / atmvol ATM隐含波动率。symbol 合约代码如 SC2609, resolution 1D/1/5(日线/分时/5日), from/to Unix秒可选默认近1年。",
       {"kind": {"type": "string", "enum": ["kline", "atmvol"], "description": "kline=K线, atmvol=ATM隐波"},
        "symbol": {"type": "string", "description": "合约代码, 如 SC2609 / 510300"},
        "resolution": {"type": "string", "description": "1D 日线 / 1 分时 / 5 5日, 默认 1D"},
        "from_ts": {"type": "integer", "description": "可选, Unix 秒起点"},
        "to_ts": {"type": "integer", "description": "可选, Unix 秒终点"}},
       ["kind", "symbol"]),
    _t("query_ovlab_search",
       "搜OpenVlab合约/标的(search-symbols): keyword 模糊匹配, 返回合约元信息列表(ticker/name/exchange/type/到期日等)。找具体合约代码用。",
       {"keyword": {"type": "string", "description": "关键词, 如 SC / 沪铜 / 510300"},
        "limit": {"type": "integer", "description": "可选, 返回条数上限, 默认 30"}},
       ["keyword"]),
    _t("query_ovlab_flow_data",
       "查期权异动资金流明细分页(OpenVlab flow-data, POST): 合约/最新价/涨跌幅/持仓量/持仓变化/成交量/成交额/买卖盘占比/OTM/DTE, 可按品种筛选。不缓存。",
       {"product": {"type": "string", "description": "可选, 品种筛选如 IO"},
        "page": {"type": "integer", "description": "页码, 默认 1"},
        "page_size": {"type": "integer", "description": "每页条数, 默认 50"}},
       []),
    _t("query_ovlab_vol_surface",
       "查波动率曲面(OpenVlab volatility-surface): 按到期月分组的 T 型报价/持仓数据。product 品种如 SC。缓存 2 分钟。",
       {"product": {"type": "string", "description": "品种代码, 如 SC / IO"}},
       ["product"]),

    # —— 研究桌：扩展行情 / 相关 / ETF 穿透 / 13F ——
    _t("query_ext_kline",
       "查扩展行情日 K: Stooq 美股 / Baostock A股 / pykrx 韩股。source=auto 按代码推断。只客观呈现历史 K, 不预测。",
       {"symbol": {"type": "string", "description": "AAPL / 600519 / 005930.KS"},
        "source": {"type": "string", "enum": ["auto", "stooq", "baostock", "pykrx"],
                   "description": "默认 auto"},
        "num": {"type": "integer", "description": "根数, 默认 60, 最大 250"}},
       ["symbol"]),
    _t("query_correlation",
       "查多标的日收益 Pearson 相关矩阵(最多 12 只)。代码用逗号: 600519,AAPL,00700.HK。客观统计, 非预测。",
       {"codes": {"type": "string", "description": "逗号分隔代码"},
        "window": {"type": "integer", "description": "回看交易日, 默认 60"}},
       ["codes"]),
    _t("query_etf_holdings",
       "查 ETF 穿透持仓。A 股走东财中报/年报全持仓(星号交叉引用不计入覆盖率); 美股走 SEC N-PORT, as_of 用 repPdDate。持仓天生滞后, 不是实时。",
       {"symbol": {"type": "string", "description": "510300 或 IVV"},
        "market": {"type": "string", "enum": ["auto", "CN", "US"], "description": "默认 auto"}},
       ["symbol"]),
    _t("query_13f",
       "查美国 13F-HR 机构持仓与最近两季环比。manager/cik 看持仓表+增减; ticker 只列提及该票的管理人。需 VR_SEC_CONTACT。客观披露, 非推荐。",
       {"manager": {"type": "string", "description": "管理人名称, 如 Berkshire"},
        "cik": {"type": "string", "description": "10 位 CIK"},
        "ticker": {"type": "string", "description": "美股代码, 列持有人"},
        "top": {"type": "integer", "description": "持仓条数, 默认 20"}},
       []),
    _t("run_backtest",
       "跑 A 股日线账户回测, 只返回净值摘要/成交笔数/未成交原因。研究模拟, 不荐股、不预测、不校准该不该买。默认次日开盘, T+1, 整手 100, 印花税只卖。",
       {"codes": {"type": "array", "items": {"type": "string"}, "description": "最多 100 个 A 股代码, 优先读本机库存"},
        "strategy": {"type": "string", "enum": ["hold", "ma_cross", "dates", "rank_mom", "top_k"], "description": "默认 hold. rank_mom 是换名单不调仓位; top_k 按目标权重加减仓. 都不是全 A 每天重选"},
        "lookback": {"type": "string", "enum": ["1y", "2y", "3y"], "description": "默认 2y"},
        "start": {"type": "string", "description": "YYYY-MM-DD, 可替代 lookback"},
        "end": {"type": "string", "description": "YYYY-MM-DD"},
        "short_win": {"type": "integer", "description": "均线短窗口, 默认 5"},
        "long_win": {"type": "integer", "description": "均线长窗口, 默认 20"},
        "mom_win": {"type": "integer", "description": "动量窗口, 默认 20"},
        "rebalance": {"type": "integer", "description": "再平衡间隔(交易日), 默认 20"},
        "oos_frac": {"type": "number", "description": "样本外占比, 如 0.3. 参数只在前段选"},
        "tune_ma": {"type": "boolean", "description": "均线是否只在样本内选, 默认 false"},
        "walk_forward": {"type": "boolean", "description": "滚动切窗, 每折新开账户"}},
       ["codes"]),
]

TOOL_NAMES = [t["function"]["name"] for t in TOOLS]

