import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

test("desktop header and phone bar share PAGE_NAV", () => {
  const header = readFileSync(join(root, "src/components/cockpit/CockpitHeader.tsx"), "utf8");
  const layout = readFileSync(join(root, "src/components/layout/Layout.tsx"), "utf8");
  assert.match(header, /export const PAGE_NAV/);
  assert.match(layout, /PAGE_NAV/);
  assert.doesNotMatch(layout, /const MOBILE_NAV/);
  assert.doesNotMatch(header, /const NAV =/);
  assert.match(header, /to: "\/backtest"/);
  assert.match(layout, /"\/backtest"/);
  assert.match(header, /to: "\/data"/);
  assert.match(layout, /"\/data"/);
  assert.match(header, /navChipClass/);
  assert.match(header, /text-\[12px\]/);
  assert.match(header, /NAV_RAIL_CLASS/);
});

test("/derivatives sits right after /a-share and is primary", () => {
  const header = readFileSync(join(root, "src/components/cockpit/CockpitHeader.tsx"), "utf8");
  const nav = header.slice(header.indexOf("export const PAGE_NAV"), header.indexOf("export function parseAShareTab"));
  const aIdx = nav.indexOf('to: "/a-share"');
  const oIdx = nav.indexOf('to: "/derivatives"');
  const fIdx = nav.indexOf('to: "/fin"');
  assert.ok(aIdx >= 0 && oIdx > aIdx && fIdx > oIdx);
  const ovlLine = nav.split("\n").find((l) => l.includes('to: "/derivatives"'));
  assert.match(ovlLine, /primary: true/);
  const arbIdx = nav.indexOf('to: "/arb"');
  const eventIdx = nav.indexOf('to: "/event"');
  const dxxIdx = nav.indexOf('to: "/dxx"');
  assert.ok(arbIdx > oIdx && arbIdx < eventIdx && eventIdx < dxxIdx && dxxIdx < fIdx);
  const arbLine = nav.split("\n").find((l) => l.includes('to: "/arb"'));
  assert.match(arbLine, /primary: true/);
  const eventLine = nav.split("\n").find((l) => l.includes('to: "/event"'));
  assert.match(eventLine, /primary: true/);
  const dxxLine = nav.split("\n").find((l) => l.includes('to: "/dxx"'));
  assert.match(dxxLine, /primary: true/);
  const researchLine = nav.split("\n").find((l) => l.includes('to: "/research"'));
  assert.match(researchLine, /primary: false/);
  assert.doesNotMatch(header, /OVL_TABS|parseOvlabTab/);
  const layout = readFileSync(join(root, "src/components/layout/Layout.tsx"), "utf8");
  assert.doesNotMatch(layout, /OVL_TABS|期权期货页签/);
  assert.match(layout, /mainRef\.current\?\.scrollTo\(0, 0\)/, "切页把手机共用滚动条拉回顶");
  const ovlab = readFileSync(join(root, "src/pages/DerivCockpit.tsx"), "utf8");
  assert.match(ovlab, /export function DerivCockpit/);
  assert.doesNotMatch(ovlab, /DerivLightChart/);
  assert.doesNotMatch(ovlab, /CtpPortfolio/);
  assert.doesNotMatch(ovlab, /VolSurfacePanel|FlowAlertPanel/);
  assert.match(layout, /pathname\.startsWith\("\/arb"\)/);
  assert.match(layout, /pathname\.startsWith\("\/event"\)/);
  assert.match(layout, /pathname\.startsWith\("\/dxx"\)/);
  const arb = readFileSync(join(root, "src/pages/ArbCockpit.tsx"), "utf8");
  assert.match(arb, /export function ArbCockpit/);
  assert.doesNotMatch(arb, /CtpPortfolio/);
  assert.doesNotMatch(arb, /ovlabMarket/);
  const router = readFileSync(join(root, "src/router.tsx"), "utf8");
  assert.match(router, /path: "\/arb"/);
  assert.match(router, /path: "\/event"/);
  assert.match(router, /path: "\/dxx"/);
  const event = readFileSync(join(root, "src/pages/EventCockpit.tsx"), "utf8");
  assert.match(event, /export function EventCockpit/);
  assert.doesNotMatch(event, /CtpPortfolio/);
  assert.doesNotMatch(event, /ovlabMarket/);
  assert.doesNotMatch(event, /useQuotes/);
  const dxx = readFileSync(join(root, "src/pages/DxxCockpit.tsx"), "utf8");
  assert.match(dxx, /export function DxxCockpit/);
  assert.match(dxx, /api\.dxxBoard/);
  assert.doesNotMatch(dxx, /CtpPortfolio/);
  assert.doesNotMatch(dxx, /ovlabMarket/);
  assert.doesNotMatch(dxx, /useQuotes/);
});

test("brand is fixed so PAGE_NAV chips do not shift", () => {
  const header = readFileSync(join(root, "src/components/cockpit/CockpitHeader.tsx"), "utf8");
  const layout = readFileSync(join(root, "src/components/layout/Layout.tsx"), "utf8");
  assert.match(header, /<Link to="\/a-share"/);
  assert.match(header, /市场研究驾驶舱/);
  assert.doesNotMatch(header, /PAGE_TITLES|brand\.to/);
  assert.doesNotMatch(header, /aria-label="A股页签"|aria-label="期权期货页签"/);
  assert.doesNotMatch(layout, /aria-label="A股页签"/);
  assert.doesNotMatch(layout, /aria-label="期权期货页签"/);
  assert.doesNotMatch(layout, /shrink-0 lg:hidden/);
});

test("A股不分复盘/K线页签, 分时日K叠在第2/3行正中", () => {
  const header = readFileSync(join(root, "src/components/cockpit/CockpitHeader.tsx"), "utf8");
  assert.doesNotMatch(header, /A_SHARE_TABS/);
  assert.doesNotMatch(header, /label: "K线"/);
  const review = readFileSync(join(root, "src/pages/DailyReview.tsx"), "utf8");
  assert.match(review, /embedded/);
  assert.match(review, /AShareLightChart/);
  assert.match(review, /pane="table"/);
  assert.match(review, /pane="charts"/);
  assert.match(review, /id: "ashare-chart"/);
  assert.match(review, /lg:h-\[30%\]/);
  assert.match(review, /lg:h-\[70%\]/);
  assert.match(review, /defaultW: 0\.30/);
  assert.match(review, /lg:w-\[30%\]/);
  assert.match(review, /lg:w-\[27%\]/);
  assert.ok(review.indexOf('id: "watch"') < review.indexOf('id: "ashare-chart"'), "自选在左下, 图在正中");
  assert.ok(review.indexOf('id: "sectors"') < review.indexOf('id: "flow"'), "首行热点左、板块资金右");
  assert.doesNotMatch(review, /pane="minute"/);
  assert.doesNotMatch(review, /自选 \/ K线/);
  const ashare = readFileSync(join(root, "src/pages/AShare.tsx"), "utf8");
  assert.match(ashare, /raw === "kline"/);
  assert.match(ashare, /p\.delete\("tab"\)/);
  const chart = readFileSync(join(root, "src/pages/AShareLightChart.tsx"), "utf8");
  assert.match(chart, /kind="minute"/);
  assert.match(chart, /setSeg\("detail"\)/);
  assert.match(chart, /setSeg\("feed"\)/);
  assert.match(chart, /embedded/);
  assert.match(chart, /AShareChartPane/);
  assert.match(chart, /pane === "charts"/);
  assert.match(chart, /grid-rows-2/);
  assert.match(chart, /BASIC_COLS/);
  assert.doesNotMatch(chart, /WatchlistCockpitPanel/);
  assert.doesNotMatch(chart, /MinuteSpark|QuoteStockRow|useMinutes/);
  const layout = readFileSync(join(root, "src/components/layout/Layout.tsx"), "utf8");
  assert.match(layout, /tab === "detail" \|\| tab === "feed"/);
  assert.doesNotMatch(layout, /A_SHARE_TABS/);
  const href = readFileSync(join(root, "src/components/cockpit/QuoteLine.tsx"), "utf8");
  assert.match(href, /\/a-share\?code=\$/);
  assert.match(href, /export function peekChartCode/);
  assert.match(href, /klineHref\(unit\)/);
  assert.match(href, /\^\(hf_\|nf_\)/);
  assert.doesNotMatch(href, /tab=kline/);
  assert.doesNotMatch(chart, /saveWatch\(\[\.\.\.loadWatch\(\), urlCode\]\)/);
  const goods = readFileSync(join(root, "src/components/cockpit/CommodityPanel.tsx"), "utf8");
  assert.match(goods, /klineHref\(c\.code\)/);
  assert.doesNotMatch(goods, /\["fut", "标的"\]/);
  assert.doesNotMatch(goods, /\["daily", "日K"\]/);
  assert.doesNotMatch(goods, /futureDaily/);
  const lk = readFileSync(join(root, "src/lib/lightKline.ts"), "utf8");
  assert.match(lk, /commodityMinutes\(COMMODITY_CODES\)/);
  assert.match(lk, /futureDaily/);
  assert.match(lk, /isFuturesCode/);
  assert.match(chart, /!isFuturesCode\(selected\)/);
});

test("A-share portfolio jumps to backtest and autostarts", () => {
  const src = readFileSync(join(root, "src/components/portfolio/StockPortfolio.tsx"), "utf8");
  assert.match(src, /\/backtest\?codes=/);
  assert.match(src, /autostart=1/);
  assert.match(src, /from=portfolio/);
  assert.match(src, /slice\(0, 100\)/);
});

test("backtest page uses store cover and meta limit", () => {
  const src = readFileSync(join(root, "src/pages/Backtest.tsx"), "utf8");
  assert.match(src, /backtestCover/);
  assert.match(src, /backtestMeta/);
  assert.match(src, /FALLBACK_MAX/);
  assert.match(src, /to="\/data"/);
  assert.match(src, /rank_mom/);
  assert.match(src, /top_k/);
  assert.match(src, /ModelPanel/);
  assert.match(src, /对照/);
  assert.match(src, /填回表单/);
  assert.match(src, /by_symbol/);
  assert.match(src, /FactorPanel/);
  assert.match(src, /stopLossPct/);
  assert.match(src, /Tearsheet/);
  assert.match(src, /IndexPoolButtons/);
  assert.match(src, /useBacktestJob/);
  const job = readFileSync(join(root, "src/pages/backtest/useBacktestJob.ts"), "utf8");
  assert.match(job, /backtestProgress/);
  const tear = readFileSync(join(root, "src/pages/backtest/Tearsheet.tsx"), "utf8");
  assert.match(tear, /月收益/);
  assert.match(tear, /最大回撤/);
  assert.match(tear, /gridTemplateColumns/);
  const factor = readFileSync(join(root, "src/pages/backtest/FactorPanel.tsx"), "utf8");
  assert.match(factor, /backtestRuns\(20, "factor"\)/);
  assert.match(factor, /写完不改/);
  assert.match(factor, /backtestFactorCompare/);
  assert.match(factor, /越小越好/);
  assert.match(factor, /IndexPoolButtons/);
  const api = readFileSync(join(root, "src/lib/api.ts"), "utf8");
  assert.match(api, /backtestIndexPool/);
});
